// =================================================================================
// resource.h — Windows resource symbol definitions for zelda3
//
// Auto-generated by the Visual Studio resource editor. Defines numeric IDs for
// resources (icons, dialogs, controls, etc.) referenced by the resource script
// zelda3.rc. The zelda3 application uses a single icon resource (the Triforce)
// which is embedded into the Win32 executable as the application icon.
//
// This file is included by both the resource compiler (rc.exe) and C source files
// that need to reference resource IDs programmatically.
// =================================================================================

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zelda3.rc
//

// Resource ID for the application icon (triforce.ico) — displayed in the taskbar,
// window title bar, Alt+Tab switcher, and Windows Explorer file listings
#define IDI_ICON1                       101

// Next default values for new objects
// These counters are used by Visual Studio's resource editor to auto-assign IDs
// when adding new resources. They are only read inside the IDE (APSTUDIO_INVOKED).
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
// Next available ID for icons, bitmaps, cursors, dialogs, and other resources
#define _APS_NEXT_RESOURCE_VALUE        102
// Next available ID for menu commands and accelerator keys
#define _APS_NEXT_COMMAND_VALUE         40001
// Next available ID for dialog box controls (buttons, text fields, etc.)
#define _APS_NEXT_CONTROL_VALUE         1001
// Next available symbol ID for the resource symbol browser
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
